### ISSUE TITLE
[补全] 3.8节遗漏图片

### ISSUE THREAD

**Issue by DSOTM-pf** [dongzl/netty-handbook#2]
3.8小节 NIO 非阻塞网络编程原理分析图 缺少图，空闲了希望能补上，不影响他人阅读体验。
- 遗漏的图片为
  ![image](https://user-images.githubusercontent.com/26241319/111271664-7906a280-866c-11eb-9b42-c790cdb6a97a.png)
- [git book 页面位置](https://dongzl.github.io/netty-handbook/#/_content/chapter03?id=_38-nio-%e9%9d%9e%e9%98%bb%e5%a1%9e%e7%bd%91%e7%bb%9c%e7%bc%96%e7%a8%8b%e5%8e%9f%e7%90%86%e5%88%86%e6%9e%90%e5%9b%be)

**Comment by dongzl** [comment]
@wowhhh 您好，感谢指正错误，已更新文档内容！
